### ISSUE TITLE
Cannot list schemas when licence end of availability is closer than 5 days

### ISSUE THREAD

**Issue by mariePredicsis** [PredicSis/predicsis-python-sdk#126]
With a license still valid for 4 days, I could not list the schemas of a project. This is in 3.7.0.
```>>> from predicsis import PredicSis
>>> pj = PredicSis.project('HDD')
>>> pj.schemas()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marcadias/.pyenv/versions/2.7.13/lib/python2.7/site-packages/predicsis/project.py", line 107, in inner
    return meth(self, *args, **kwargs)
  File "/Users/marcadias/.pyenv/versions/2.7.13/lib/python2.7/site-packages/predicsis/sdk.py", line 50, in _inner
    return meth(self, *args, **kwargs)
  File "/Users/marcadias/.pyenv/versions/2.7.13/lib/python2.7/site-packages/predicsis/project.py", line 579, in schemas
    all_schm.append(SchemaWithModel(self, lambda: mod))
  File "/Users/marcadias/.pyenv/versions/2.7.13/lib/python2.7/site-packages/predicsis/schema/__init__.py", line 535, in __init__
    pipe_fs = PipeResource('LoadFS', prepipe, lambda: init_fs(prepipe))
  File "/Users/marcadias/.pyenv/versions/2.7.13/lib/python2.7/site-packages/predicsis/pipeline.py", line 51, in __init__
    self.update()
  File "/Users/marcadias/.pyenv/versions/2.7.13/lib/python2.7/site-packages/predicsis/logger.py", line 90, in _inner
    res = func(*args, **kwargs)
  File "/Users/marcadias/.pyenv/versions/2.7.13/lib/python2.7/site-packages/predicsis/pipeline.py", line 78, in update
    self._result = self._action()
  File "/Users/marcadias/.pyenv/versions/2.7.13/lib/python2.7/site-packages/predicsis/schema/__init__.py", line 535, in <lambda>
    pipe_fs = PipeResource('LoadFS', prepipe, lambda: init_fs(prepipe))
  File "/Users/marcadias/.pyenv/versions/2.7.13/lib/python2.7/site-packages/predicsis/schema/__init__.py", line 530, in init_fs
    fs = APIFeatureSet.create('Schema', project.directory())
  File "/Users/marcadias/.pyenv/versions/2.7.13/lib/python2.7/site-packages/predicsis/licence_authority.py", line 40, in inner
    warning(delta.days)
  File "/Users/marcadias/.pyenv/versions/2.7.13/lib/python2.7/site-packages/predicsis/licence_authority.py", line 18, in warning
    if WARNING_NOT_PROVIDED:
UnboundLocalError: local variable 'WARNING_NOT_PROVIDED' referenced before assignment```

**Comment by jeanbaptistepriez** [comment]
@mariePredicsis could you check if the PR #127 fix the problem please?

**Comment by mariePredicsis** [comment]
Good now 👏
